--- 
- hosts: localhost
  gather_facts: no
  become: no

  tasks:
    - name: Unpause MCO
      k8s:
        state: present
        merge_type: merge

        definition:
          apiVersion: machineconfiguration.openshift.io/v1
          kind: MachineConfigPool
          
          metadata:
            name: "{{item}}"
    
          spec:
            paused: false
      loop:
        - master
        - worker